# Use official Tomcat 8 image
FROM tomcat:8.5-jdk8

# Set environment variables
ENV CATALINA_HOME /usr/local/tomcat

# Remove default webapps (optional, for cleaner deployment)
RUN rm -rf $CATALINA_HOME/webapps/*

# Copy your WAR file to Tomcat webapps directory
COPY target/Project.war $CATALINA_HOME/webapps/ROOT.war

# Expose port 8080
EXPOSE 8080

# Start Tomcat
CMD ["catalina.sh", "run"]
